#!/usr/bin/python3.6
import os

os.environ["DISPLAY"] = ':0'

MODEL_PATH = "/opt/econ/dlapp/smartecam-ai-samples/models/trt_head_detection_FP16.pb"

import econ
econ.start_people_counting(MODEL_PATH)
